apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: # base64 encoded value of mongo-root-username:
  mongo-root-password: # base64 encoded value of mongo-root-password:
